//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDeThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDiem
    {
        public BangDiem()
        {
            this.rowguid = Guid.NewGuid();
        }
        public string MAMH { get; set; }
        public string MASV { get; set; }
        public short LAN { get; set; }
        public Nullable<System.DateTime> NGAYTHI { get; set; }
        public Nullable<double> DIEM { get; set; }
        public string BAITHI { get; set; }
        public System.Guid rowguid { get; set; }
        
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
