//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDeThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoDe
    {
        public BoDe()
        {
            this.rowguid = Guid.NewGuid();
        }
        public int CAUHOI { get; set; }
        public string MAMH { get; set; }
        public string TRINHDO { get; set; }
        public string NOIDUNG { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string DAPAN { get; set; }
        public string MAGV { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
