//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDeThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien_DangKy
    {
        public GiaoVien_DangKy()
        {
            this.rowguid = Guid.NewGuid();
        }
        public string MAGV { get; set; }
        public string MALOP { get; set; }
        public string MAMH { get; set; }
        public string TRINHDO { get; set; }
        public Nullable<System.DateTime> NGAYTHI { get; set; }
        public short LAN { get; set; }
        public Nullable<short> SOCAUTHI { get; set; }
        public Nullable<short> THOIGIAN { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual Lop Lop { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
