//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDeThi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KQ_Thi
    {
        public KQ_Thi()
        {
            this.rowguid = Guid.NewGuid();
        }
        public string MSV { get; set; }
        public string MAMH { get; set; }
        public Nullable<int> LAN { get; set; }
        public Nullable<int> CAUHOI { get; set; }
        public string CHOSE { get; set; }
        public string DAPAN { get; set; }
        public int id { get; set; }
        public Nullable<int> Correct { get; set; }
        public string NgayThi { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
