//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDeThi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DETHI_DBEntities : DbContext
    {
        public DETHI_DBEntities()
            : base("name=DETHI_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangDiem> BangDiems { get; set; }
        public virtual DbSet<BoDe> BoDes { get; set; }
        public virtual DbSet<CoSo> CoSoes { get; set; }
        public virtual DbSet<GiaoVien> GiaoViens { get; set; }
        public virtual DbSet<GiaoVien_DangKy> GiaoVien_DangKy { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Lop> Lops { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<KQ_Thi> KQ_Thi { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_test(string mASV)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_test", mASVParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_kiemtraMaKhoa(string mAKH)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_kiemtraMaKhoa", mAKHParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_kiemtraMaGV(string mAGV)
        {
            var mAGVParameter = mAGV != null ?
                new ObjectParameter("MAGV", mAGV) :
                new ObjectParameter("MAGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_kiemtraMaGV", mAGVParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_kiemtraMaLop(string mALOP)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_kiemtraMaLop", mALOPParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_kiemtraMaSV(string mASV)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_kiemtraMaSV", mASVParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_kiemtraMaGV1(string mAGV)
        {
            var mAGVParameter = mAGV != null ?
                new ObjectParameter("MAGV", mAGV) :
                new ObjectParameter("MAGV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_kiemtraMaGV1", mAGVParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_kiemtraMaKhoa1(string mAKH)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_kiemtraMaKhoa1", mAKHParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_kiemtraMaLop1(string mALOP)
        {
            var mALOPParameter = mALOP != null ?
                new ObjectParameter("MALOP", mALOP) :
                new ObjectParameter("MALOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_kiemtraMaLop1", mALOPParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_kiemtraMaSV1(string mASV)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_kiemtraMaSV1", mASVParameter);
        }
    }
}
